spring.application.name=solarquote

# Conexao com o PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/sistema_orcamentos
spring.datasource.username=postgres
spring.datasource.password=8754

# Nao deixar o Hibernate criar/alterar tabelas sozinho.
spring.jpa.hibernate.ddl-auto=validate

# Mostra o SQL gerado no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
solarquote.jwt.secret=troque-esta-chave-por-uma-bem-longa-e-dificil-de-adivinhar-123456
solarquote.jwt.expiracao-ms=86400000